site :opscode

metadata

cookbook "rsc_remote_recipe", github: 'rightscale-services-cookbooks/rsc_remote_recipe'
cookbook "rs-storage", github: 'rightscale-cookbooks/rs-storage'


group :integration do
  cookbook 'apt', '~> 2.6.0'
  cookbook 'yum-epel', '~> 0.4.0'
 # cookbook 'curl', '~> 1.1.0'
 # cookbook 'fake', path: './test/cookbooks/fake'
 # cookbook 'rhsm', '~> 1.0.0'
end