default[:couchbase][:install_dir] = '/opt/couchbase'
default[:couchbase][:conf_dir] = node[:CB][:install_dir] + '/conf'
default[:couchbase][:lib_dir] = node[:CB][:install_dir] + '/lib'
default[:couchbase][:data_dir] = node[:CB][:install_dir] + '/data'
default[:couchbase][:storage_type] = 'ephemeral'
default[:couchbase][:initial_launch] = 'TRUE'
